# Python Essentials and NumPy Notebook

In this notebook, we will explore the fundamental concepts of **Python** and the **NumPy** library, essential tools for scientific computing and data science.

**Part 1 – Python Essentials**: variables, data types, fundamental structures (lists, tuples, dictionaries, sets), operators, functions, control structures, and library imports.

**Part 2 – NumPy**: creation and properties of arrays, mathematical operations, indexing and slicing, reshaping, statistical functions, and utilities for generating arrays and random numbers.

Each Task includes: a brief explanation, sample code, and interpretation of the results.

In [1]:
# Setup Environment

#!pip install numpy
import numpy as np
print("Environment ready — NumPy installed and imported.")

Environment ready — NumPy installed and imported.


## Part 1 – Python Essentials

### Task 1 – Variables and Data Types

Variables allow for the storage of values. In Python, it is not necessary to declare their type.

In [2]:
integer_num = 10
decimal_num = 3.14
text = "Python"

print("Integer:", integer_num, ",type:", type(integer_num))
print("Float:", decimal_num, ",type:", type(decimal_num))
print("String:", text, ",type:", type(text))

Integer: 10 ,type: <class 'int'>
Float: 3.14 ,type: <class 'float'>
String: Python ,type: <class 'str'>


Let's consider three variables of different types: integer, float, and string.

### Task 2 – Lists

Lists are ordered collections enclosed in square brackets. They can be modified.

In [3]:
numbers = [1, 2, 3]
numbers.append(4)
print("Updated list:", numbers)

Updated list: [1, 2, 3, 4]


The initial list `[1, 2, 3]` has been updated to `[1, 2, 3, 4]`.

### Task 3 – Tuple

Tuples are similar to lists, but they are **immutable**.

In [4]:
coordinates = (10, 20, 30)
print("Tuple:", coordinates)

Tuple: (10, 20, 30)


The tuple `(10, 20, 30)` cannot be modified after its creation.

### Task 4 – Dictionaries

Dictionaries store key-value pairs.

In [5]:
student = {"name": "Anna", "program": "Genomic Data Science", "year": 2025}
print("Dictionary:", student)
print("Name:", student["name"])

Dictionary: {'name': 'Anna', 'program': 'Genomic Data Science', 'year': 2025}
Name: Anna


The dictionary associates keys with values. With `studente["nome"]`, we obtain 'Anna'.

### Task 5 – Set

Sets are unordered collections of unique elements.

In [6]:
unique_set = {1, 2, 3, 3, 2}
print("Set:", unique_set)

Set: {1, 2, 3}


The duplicates are removed, leaving only `{1, 2, 3}`.

### Task 6 – Mathematical and Logical Operators

Operators enable calculations and comparisons.

In [7]:
a, b = 7, 3
print("Sum:", a + b)
print("Difference:", a - b)
print("Product:", a * b)
print("Division:", a / b)
print("Is a > b?", a > b)
print("Is a == b?", a == b)

Sum: 10
Difference: 4
Product: 21
Division: 2.3333333333333335
Is a > b? True
Is a == b? False


Let's examine the results of arithmetic operations and logical comparisons.

### Task 7 – Functions

Functions allow for the reuse of blocks of code.

In [8]:
def square(x):
    return x**2

print("Square of 5:", square(5))

Square of 5: 25


The function calculates the square of the given input number.

### Task 8 – Control Structures

Conditional statements and loops.

In [9]:
x = 4
if x > 0:
    print("x is positive")
else:
    print("x is not positive")

x is positive


In [10]:
nums = [1, 2, 3]
for i in nums:
    print("Iteration:", i)

Iteration: 1
Iteration: 2
Iteration: 3


In [11]:
y = 0
while y < 3:
    print("y:", y)
    y += 1

y: 0
y: 1
y: 2


The `if` statement manages conditions, `for` iterates over a list, and `while` repeats as long as the condition is true.

## Part 2 – NumPy

### Task 9 – Creation of Arrays

NumPy arrays are similar to lists, but optimized for calculations.

In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])
print("1D Array:", a)
print("2D Array:\n", b)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


The first is a vector, the second is a 2x3 matrix.

### Task 10 – Properties of Arrays

Arrays have properties such as shape, dimensions, and data type.

In [13]:
print("Shape:", b.shape)
print("Dimensions:", b.ndim)
print("Data type:", b.dtype)

Shape: (2, 3)
Dimensions: 2
Data type: int64


This information describes the structure of the array.

### Task 11 – Operations on Arrays

The operations are applied element by element.

In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print("Sum:", x + y)
print("Product:", x * y)
print("Square:", x ** 2)

Sum: [5 7 9]
Product: [ 4 10 18]
Square: [1 4 9]


Each operation is performed on each element.

### Task 12 – Indexing and Slicing

We can select elements or sub-arrays using indices.

In [15]:
v = np.array([10, 20, 30, 40, 50])
print("First element:", v[0])
print("Last element:", v[-1])
print("Sub-array:", v[1:4])

First element: 10
Last element: 50
Sub-array: [20 30 40]


We obtain single values or ranges of values.

### Task 13 – Reshape

With `reshape`, we change the shape of an array without altering its data.

In [16]:
m = np.arange(12)
M = m.reshape(3, 4)
print("Array:", m)
print("3x4 Matrix:\n", M)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The function `reshape(3,4)` transforms the vector into a 3x4 matrix.

### Task 14 – Statistical Functions

NumPy includes functions for mean, standard deviation, and sum.

In [17]:
data = np.array([2, 4, 6, 8, 10])
print("Mean:", np.mean(data))
print("Standard deviation:", np.std(data))
print("Sum:", np.sum(data))

Mean: 6.0
Standard deviation: 2.8284271247461903
Sum: 30


We obtain basic statistics on the data.

### Task 15 – Utility Functions

Functions for quickly creating arrays.

In [18]:
print("Arange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((2, 3)))
print("Random values:\n", np.random.rand(2, 3))

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Random values:
 [[0.07163509 0.14858069 0.63389804]
 [0.35417843 0.2445332  0.00229602]]


We can generate sequences, arrays of zeros, ones, and random numbers.

# Conclusion

In this notebook, we introduced the fundamentals of **Python** (variables, data structures, operators, functions, and control statements) and the main features of **NumPy** (arrays, properties, operations, slicing, reshaping, and statistical/utilitarian functions).

These skills form the foundation for more advanced analyses and will serve as the starting point for utilizing libraries such as **Pandas**, **Matplotlib**, and **Seaborn** for data management and visualization.